# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=255, verbose_name='Наименование работодателя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('employer_site', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('date_from', models.DateField(verbose_name='Начало периода работы')),
                ('date_to', models.DateField(verbose_name='Окончание периода работы')),
            ],
        ),
    ]
