# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('vendor', models.CharField(max_length=255, verbose_name='Образовательное учреждение или учебный центр')),
                ('vendor_site', models.URLField(blank=True)),
                ('period', models.DateField(verbose_name='Год обучения')),
                ('relevant', models.BooleanField(default=False, verbose_name='Отношение к рассматриваемой теме')),
            ],
        ),
        migrations.CreateModel(
            name='HighEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование ВУЗА')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('department', models.CharField(choices=[('дневное', 'дневное'), ('вечернее', 'вечернее'), ('заочное', 'заочное')], default=('дневное', 'дневное'), max_length=50, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=255, verbose_name='Наименование работодателя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('employer_site', models.URLField(blank=True, verbose_name='Сайт')),
                ('date_from', models.DateField(verbose_name='Начало периода работы')),
                ('date_to', models.DateField(verbose_name='Окончание периода работы')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('next_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Псевдоним(ы)')),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='Путь к файлу фотографии')),
                ('descriptions', models.TextField(blank=True, verbose_name='Личные качества')),
                ('date_of_birth', models.DateField(blank=True, default='2001-01-01', verbose_name='Дата рождения')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Место жительства')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Гражданство')),
                ('education', models.CharField(blank=True, max_length=50, verbose_name='Образование')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
