# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('adress', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
                ('zip_code', models.CharField(blank=True, max_length=6, verbose_name='Почтовый индекс')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='employer_site',
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization'),
        ),
    ]
