# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160701_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('vendor', models.CharField(max_length=255, verbose_name='Образовательное учреждение или учебный центр')),
                ('vendor_site', models.URLField(blank=True)),
                ('period', models.DateField(verbose_name='Год обучения')),
                ('relevant', models.BooleanField(default=False, verbose_name='Отношение к рассматриваемой теме')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('next_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Псевдоним(ы)')),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='employer_site',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
