# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20160704_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование ВУЗА')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('department', models.CharField(choices=[('дневное', 'дневное'), ('вечернее', 'вечернее'), ('заочное', 'заочное')], default=('дневное', 'дневное'), max_length=50, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, default='0000-00-00', verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='descriptions',
            field=models.TextField(blank=True, verbose_name='Личные качества'),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=50, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.CharField(blank=True, max_length=100, verbose_name='Путь к файлу фотографии'),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Место жительства'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Гражданство'),
        ),
    ]
